name: CR001 CI

on:
  pull_request:
    branches: [ main ]

permissions:
  id-token: write # This is REQUIRED for OIDC
  contents: read  # This is REQUIRED for Checkout

jobs:
  cr001-ci:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # This is REQUIRED for OIDC
      contents: read  # This is REQUIRED for Checkout

    environment: CI
    env:
      SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
      SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
      SNOWFLAKE_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}
      SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
      SNOWFLAKE_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE }}
      SNOWFLAKE_SCHEMA: ${{ secrets.SNOWFLAKE_SCHEMA }}
      SNOWFLAKE_PRIVATE_KEY: ${{ secrets.SNOWFLAKE_PRIVATE_KEY }}

      TF_VAR_snowflake_account: ${{ secrets.SNOWFLAKE_ACCOUNT }}
      TF_VAR_snowflake_username: ${{ secrets.SNOWFLAKE_USER }}
      TF_VAR_snowflake_role: ${{ secrets.SNOWFLAKE_ROLE }}
      TF_VAR_snowflake_private_key_path: /home/runner/.ssh/snowflake_key.pem


    defaults:
      run:
        working-directory: cicd_demo


    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::448033706053:role/githubconnect
          aws-region: us-east-2

      
      - name: Write Snowflake private key
        run: |
          mkdir -p /home/runner/.ssh
          echo "$SNOWFLAKE_PRIVATE_KEY" > /home/runner/.ssh/snowflake_key.pem
          chmod 600 /home/runner/.ssh/snowflake_key.pem

      # --- TERRAFORM SECTION ---
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.7.0" # Use your preferred version

      - name: Terraform Init
        working-directory: tf_demo
        run: terraform init
      

      - name: Terraform Plan
        working-directory: tf_demo
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        working-directory: tf_demo
        run: terraform apply -auto-approve tfplan

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create dbt profiles.yml
        run: |
          mkdir -p ~/.dbt
          cat << EOF > ~/.dbt/profiles.yml
          cicd_demo:
            outputs:
              ci:
                type: snowflake
                account: ${SNOWFLAKE_ACCOUNT}
                user: ${SNOWFLAKE_USER}
                role: ${SNOWFLAKE_ROLE}
                warehouse: ${SNOWFLAKE_WAREHOUSE}
                database: ${SNOWFLAKE_DATABASE}
                schema: ${SNOWFLAKE_SCHEMA}
                authenticator: snowflake
                private_key_path: /home/runner/.ssh/snowflake_key.pem

                threads: 1
            target: ci
          EOF

      - name: Check private key injected (safe)
        run: |
          echo "KEY_LENGTH=${#SNOWFLAKE_PRIVATE_KEY}"

      - name: dbt debug
        run: dbt debug 

      - name: dbt deps
        run: dbt deps 


      - name: dbt build (modified models only)
        run: dbt build --fail-fast


