name: CR001 CD

on:
  push:
    branches:
      - main

jobs:
  cr001-cd:
    runs-on: ubuntu-latest
    environment: CD
    env:
      SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
      SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
      SNOWFLAKE_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}
      SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
      SNOWFLAKE_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE }}
      SNOWFLAKE_SCHEMA: ${{ secrets.SNOWFLAKE_SCHEMA }}
      SNOWFLAKE_PRIVATE_KEY: ${{ secrets.SNOWFLAKE_PRIVATE_KEY }}
    defaults:
      run:
        working-directory: cicd_demo


    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
        
      - name: Write Snowflake private key
        run: |
          mkdir -p /home/runner/.ssh
          echo "$SNOWFLAKE_PRIVATE_KEY" > /home/runner/.ssh/snowflake_key.pem
          chmod 600 /home/runner/.ssh/snowflake_key.pem

      - name: Create dbt profiles.yml
        run: |
          mkdir -p ~/.dbt
          cat << EOF > ~/.dbt/profiles.yml
          cicd_demo:
            outputs:
              cd:
                type: snowflake
                account: ${SNOWFLAKE_ACCOUNT}
                user: ${SNOWFLAKE_USER}
                role: ${SNOWFLAKE_ROLE}
                warehouse: ${SNOWFLAKE_WAREHOUSE}
                database: ${SNOWFLAKE_DATABASE}
                schema: ${SNOWFLAKE_SCHEMA}
                authenticator: snowflake
                private_key_path: /home/runner/.ssh/snowflake_key.pem
                threads: 1
            target: cd
          EOF

      - name: dbt debug
        run: dbt debug 

      - name: dbt deps
        run: dbt deps 

      - name: dbt build (deploy to prod)
        run: dbt build 

      - name: dbt test
        run: dbt test
