name: CR001 CD

on:
  push:
    branches:
      - main

jobs:
  cr001-cd:
    runs-on: ubuntu-latest
    environment: CD
    defaults:
      run:
        working-directory: cicd_demo


    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create dbt profiles.yml
        run: |
          mkdir -p ~/.dbt
          cat << EOF > ~/.dbt/profiles.yml
          cicd_demo:
            outputs:
              cd:
                type: snowflake
                account: ${{ secrets.SNOWFLAKE_ACCOUNT }}
                user: ${{ secrets.SNOWFLAKE_USER }}
                password: ${{ secrets.SNOWFLAKE_PASSWORD }}
                role: ${{ secrets.SNOWFLAKE_ROLE }}
                database: ${{ secrets.SNOWFLAKE_DATABASE }}
                warehouse: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
                schema: ${{ secrets.SNOWFLAKE_SCHEMA }}
                threads: 1
            target: cd
          EOF

      - name: dbt debug
        run: dbt debug 

      - name: dbt deps
        run: dbt deps 

      - name: dbt build (deploy to prod)
        run: dbt build 

      - name: dbt test
        run: dbt test
